/**
 * Copyright (c) 2009 Anders Ruud
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


package sheep.input;

import android.view.MotionEvent;

/**
 * Objects can subscribe to touch events by implementing this interface. 
 */
public interface TouchListener {
	
	/**
	 * Called when the user touches down on the screen.
	 * @param event The event generated by the action.
	 * @return True if the event was consumed, false otherwise.
	 */
	public boolean onTouchDown(MotionEvent event);
	
	/**
	 * Called when the user releases a touch from the screen.
	 * @param event The event generated by the action.
	 * @return True if consumed, false otherwise.
	 */
	public boolean onTouchUp(MotionEvent event);
	
	/**
	 * Called when the user drags a touch along the screen.
	 * @param event The event generated by the action.
	 * @return True if consumed, false otherwise.
	 */
	public boolean onTouchMove(MotionEvent event);
	
}